Fix docstring comment for constants
rust-lang/rust-bindgen pull request #2027
Opened 2021-04-10 16:47 UTC by nicochatzi

As a first contribution, here's a small and possibly quite naive fix and test for #1995  :)

2021-04-10 16:47 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!

2021-04-11 17:41 UTC, emilio requested changes
just one minor change to handle the edge cases. With that fixed it looks great, thanks!

2021-04-11 17:41 UTC, emilio commented on src/codegen/mod.rs
> +        }
There's some places here were we could still bail out without generating the constant. Instead, let's move the `let mut attrs = vec![];` from below to here, and append to `attrs`.

With that fixup, this looks great, thanks!

2021-04-11 21:14 UTC, emilio approved these changes
Looks good, thanks!

2021-04-11 21:15 UTC, merged

2021-04-11 21:16 UTC, nicochatzi commented
Cool, thanks @emilio!