Canonicalize types before looking for their definitions.
rust-lang/rust-bindgen pull request #2084
Opened 2021-07-29 04:18 UTC by pcwalton

In some esoteric cases involving nested templates,
`ty.declaration().definition()` isn't enough to find the definition: we need
`ty.canonical_type().declaration().definition()` instead.

Closes #2078.

r? @emilio

2021-07-29 04:18 UTC, highfive commented
<img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20> **Warning** <img src="http://www.joshmatthews.net/warning.svg" alt="warning" height=20>

* These commits modify **unsafe code**. Please review it carefully!

2021-07-29 21:46 UTC, emilio approved these changes
Thank you!

It's really weird that we need the canonical type, there and that clang doesn't figure out the definition, but this looks good to me.

2021-07-29 21:51 UTC, dtolnay requested changes
According to the test failure on `tests/headers/layout_cmdline_token.h` / `tests/expectations/tests/layout_cmdline_token.rs` one of the expected outputs needs to be regenerated.

```diff
+/// Stores a pointer to the ops struct, and the offset: the place to
+/// write the parsed result in the destination structure.
 pub type cmdline_parse_token_hdr_t = cmdline_token_hdr;

...

thread 'header_layout_cmdline_token_h' panicked at 'Header and binding differ! Run with BINDGEN_OVERWRITE_EXPECTED=1 in the environment to automatically overwrite the expectation or with BINDGEN_TESTS_DIFFTOOL=meld to do this manually.'
```

2021-07-31 11:33 UTC, emilio approved these changes

2021-07-31 11:33 UTC, merged