implement clone on builder
rust-lang/rust-bindgen pull request #2134
Opened 2021-12-10 01:12 UTC by jrandall

Implements `Clone` on `Builder` (and all of the types included within it). Most were straightforward and I simply added derive Clone on the structs, except for the boxed `ParseCallbacks` since it is a trait. I have used the `dyn-clone` crate to make this work, provided that the underlying type implementing the trait implements Clone itself.

Notably, this does mean that any type used to implement `ParseCallbacks` that does not implement `Clone` would cause a compilation failure, although I imagine in most cases it should be a simple matter of adding `#[derive(Clone)]` to the type. Every example I've seen uses a unit struct for the `ParseCallbacks` implementation, so I guess it would be very easy to fix, but it would nonetheless be a breaking change since code that previously worked would fail to compile after this change until a Clone implementation is added to the type implementing `ParseCallbacks`. 

The changes made to the parse callbacks tests illustrate the simple fix that would need to be made to client code: https://github.com/rust-lang/rust-bindgen/commit/97fed5531db5ec2e55426f2fe2262e1c3de0d40c

Closes #2132

2021-12-10 01:35 UTC, jrandall commented
Spoke too soon - I now see that the `bindgen-integration` tests are failing due to `MacroCallback` not implementing `Clone`, and the use case there involves a HashSet and some Mutex-protected counters that don't really make sense to clone. 

I suppose an option might be to put implementing Clone on Builder behind a feature gate so that it can be opted-in to when the ability to clone is desired and the need to implement Clone for any ParseCallbacks in use is trvial (or worth the effort). 

I'll give that a try.

2021-12-29 19:24 UTC, emilio requested changes

2021-12-29 19:24 UTC, emilio commented on src/clang.rs
> +#[derive(Clone)]
This is not safe. `UnsavedFile` keeps pointers to its inner `CString`s so at the very least the clone implementation needs to be more subtle.

2021-12-29 19:24 UTC, emilio commented on tests/parse_callbacks/mod.rs
> +#[derive(Clone, Debug)]
Why is this needed?

2021-12-29 19:24 UTC, emilio commented on src/callbacks.rs
> +dyn_clone::clone_trait_object!(ParseCallbacks);
Can you elaborate on why this is needed instead of just having `ParseCallbacks: Clone`?

2021-12-29 19:24 UTC, emilio commented on src/callbacks.rs
> +pub trait ParseCallbacks:
It is really unfortunate to duplicate all the trait here. Can we avoid this by using a macro instead?

2021-12-29 19:30 UTC, emilio commented
I think I'd rather move most of the options to an inner struct and make _that_ clone than this. That said, can't you solve your use-case in #2132 by keeping the custom options in your own data structure or something updating both builders? Or just move the setup to its own function? So something like:


```rust
fn setup_builder(builder: &mut Builder) {
  // All your complex code, call this function twice.
}
```

Or:

```rust
let mut extra_flags = vec![];
// Compute your flags.

for builder in [&mut with_comments, &mut without_comments] {
    builder....
}
```

2022-02-18 19:13 UTC, closed without merging