Derive from any other trait only when deriving from Copy
rust-lang/rust-bindgen pull request #2200
Opened 2022-05-04 15:15 UTC by vadorovsky

It's impossible to #[derive] from any other trair when not deriving from
Copy when using the newest Rust nightly. Any attempt to do that results
in the following error:

```
error: `#[derive]` can't be used on a `#[repr(packed)]` struct that does not derive Copy (error E0133)
```

Fixes: #2083
Signed-off-by: Michal Rostecki <vadorovsky@gmail.com>

2022-05-04 17:03 UTC, emilio requested changes
We should do this only when the struct is packed, or what am I missing? Otherwise it might break existing code gratuitously.

2022-05-04 18:03 UTC, vadorovsky commented
@emilio Good point, it should be fixed now.

2022-05-04 23:01 UTC, emilio approved these changes
Thanks, looks good! I think we can simplify it slightly (given we always treat `packed = None` as `false`, but let me know if I'm missing something.

Looks good to me with that.

2022-05-04 23:01 UTC, emilio commented on src/codegen/mod.rs
> +                        let derivable_traits = derives_of_item(item, ctx, None);
And change this to either:

```rust
let packed = false; // Enums can't be packed in Rust
let derivable_traits = derives_of_item(item, ctx, packed);
```

Or just:

```rust
let derivable_traits = derives_of_item(item, ctx, /* packed = */ false);
```

2022-05-05 08:00 UTC, vadorovsky commented on src/codegen/mod.rs
> +    packed: Option<bool>,
Good idea, done

2022-05-05 08:01 UTC, vadorovsky commented
Thank you for review! I like the idea with using just bool without Option, I applied it.

2022-05-07 22:52 UTC, emilio approved these changes
Thanks, this looks good for now. I _think_ this might not be fully correct in the presence of a non-packed struct containing a packed struct... For that we probably need to track this properly in the `CanDerive` analysis.

That shouldn't be too hard, but doing this in the meantime is fine.

2022-05-07 22:52 UTC, merged

2022-05-08 10:46 UTC, vadorovsky commented
@emilio Good call, I will try to address that in a separate PR