Split `BindgenOptions`
rust-lang/rust-bindgen pull request #2263
Opened 2022-09-05 21:35 UTC by pvdrz

This PR splits the `BindgenOptions` struct into two:
- `BindgenOptions`: Which holds all the command line arguments and implements `Clone`.
- `BindgenState`: Which holds the remaining fields of `BindgenOptions` and does not implement `Clone`.

This change would allow bindgen to preserve its initial configuration and run again if required (which would help solve #1090).

It would also ease a transition to a newer version of clap.

cc @emilio @amanjeev

2022-09-10 01:19 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably 8b29355ca0ce54e941d398ef9a605e9b5c0f20ae) made this pull request unmergeable. Please resolve the merge conflicts.

2022-09-11 13:31 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably 61636e94ca315278d9ac5f1210ffca6cca697428) made this pull request unmergeable. Please resolve the merge conflicts.

2022-09-19 00:14 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably 0d805d70d5c6e4cc99cbad7a988c38bdfe52321b) made this pull request unmergeable. Please resolve the merge conflicts.

2022-09-23 06:28 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably 86f059f081160ba01de31fc2ec6e20e52b97968d) made this pull request unmergeable. Please resolve the merge conflicts.

2022-09-23 07:50 UTC, emilio requested changes
So this is a pretty massive change, and I'm not sure it's warranted.

From a quick look, the things in `BindgenOptions` that can't be cloned are `input_unsaved_files` and the `ParseCallbacks`.

`input_unsaved_files` seems rather trivial to get rid of (just a matter of generating the `UnsavedFile` list in `generate` rather than the caller unless I'm missing something).

The `ParseCallbacks` seem like similarly could be passed separately from `BindgenOptions` as an extra argument to `generate` etc, unless I'm missing something.

That leaves the weird mutations that we do on the clang flags and so. Those don't seem impossible to remove (we could make the options immutable I think). But also, not sure we'd need to. As long as we clone the options before calling `generate()`, we can call `generate()` again with the same set of options and it should work.

That is to say, I think this can be done in a much less intrusive way, wdyt?

2022-09-23 16:37 UTC, pvdrz commented
I agree that it would be possible to preserve the user inputs by just cloning `BindgenOptions` before calling `generate`. But at the same time, I believe this change makes clearer when a value was set by the user with some intent vs when bindgen modified one value due to its internal logic.

At the same time, keeping all the CLI inputs in a single type makes easier moving to things like clap 3 with its `derive` macro. Which would ease adding new flags and keeping the documentation and names consistent as they would be a bunch of field attributes instead of being on a different file.

I'm not opposed to just cloning things before they are changed. I just think this makes the code a bit more organized while only adding the extra burden of thinking if something is part of the inputs or part of the state to decide where to find it. At the end most of the changes done to the uses of `BindgenOptions` were reduced to doing
```diff
+ foo.options()
- foo.inputs()
```

2022-09-24 02:24 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #2278) made this pull request unmergeable. Please resolve the merge conflicts.

2022-09-26 18:23 UTC, closed without merging

2022-09-28 19:11 UTC, divagant-martian commented
Sad to this closed, seemed like a good code quality improvement