Emulate variadic methods using tuples
rust-lang/rust-bindgen pull request #2276
Opened 2022-09-20 20:09 UTC by pvdrz

This PR introduces a new flag `--tuple-varargs-len=<LEN>` which can be used to emulate variadic methods using tuples of length up to `<LEN>`.

# Example
If the generated function signature for a variadic method is:
```rust
extern "C" {
    fn foo_bar(foo: &Foo, a: A, ...);
}
```
and the `--tuple-varargs-len` flag is set. A new method for the type `Foo` is introduced:
```rust
impl Foo {
    unsafe fn bar(&self, a: A, varargs: impl VarArgs) {
        varargs.call_foo_bar(self, a)
    }
}
```
The user would use such method like this:
```rust
foo.bar(a, ()); // 0 variadic args
foo.bar(a, (10,)); // 1 variadic arg
foo.bar(a, (10, b"hello")); // 2 variadic args
foo.bar(a, (10, b"hello", false)); // 3 variadic args
...
```
To do this, the `VarArgs` trait is declared and implemented automatically up to the value of `--tuple-varargs-len`:
```rust
trait VarArgs {
    unsafe fn call_foo_bar(self, foo: &Foo, a: A);
}

impl VarArgs for () {
    unsafe fn call_foo_bar(self, foo: &Foo, a: A) {
        let () = self;
        foo_bar(foo, a)
    }
}

impl<T0> VarArgs for (T0,) {
    unsafe fn call_foo_bar(self, foo: &Foo, a: A) {
        let (t0, ) = self;
        foo_bar(foo, a, t0)
    }
}

impl<T0, T1> VarArgs for (T0, T1) {
    unsafe fn call_foo_bar(self, foo: &Foo, a: A) {
        let (t0, t1) = self;
        foo_bar(foo, a, t0, t1)
    }
}
```
This has some disadvantages, such as the user not being able to just do `foo.bar(a)` or `foo,bar(a, v)` without getting somewhat confusing errors but this could be mitigated by properly documenting the `VarArgs` trait.

Fixes #407

2022-09-23 07:07 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably 4b006da21bd7a6701c8e7f658085569830207c9c) made this pull request unmergeable. Please resolve the merge conflicts.

2022-09-23 07:09 UTC, emilio reviewed
I'm not sure how I feel about this, do you really think that this is worth it? As in, do you think that doing:

```
foo.printf(b"%d\0".as_ptr(), (a, b, c))
```

Is realistically much better than:

```
Foo_printf(foo, b"%s\0".as_ptr(), a, b, c)
```

?

2022-09-23 16:54 UTC, pvdrz commented
The pros I see with approach are:
1. Method calls are generally shorter: `foo.printf(` is already shorter than `Foo_printf(foo, `. Which offsets the cost of adding `(` and `)` for variadic arguments unless the types and methods have single letter identifiers in which case both are the same length i think.
2. You don't have to worry about deref: Autoderef makes easier to put `Foo` behind any kind of smart pointer and still be able to call methods on it. Basically `foo.printf(` vs `Foo_printf(&*foo, `.
3. More consistency while calling methods: In the current state, if you generate bindings for several methods and one of them turns out to be variadic, you have to remember that it will only be available as a free function. The extreme case would be typing `foo.` and wondering why `printf` does not appear between your suggestions, then have to go back to the generated bindings and see that `Foo_printf` is what you need. With this change any variadic method can be called with the dot syntax just like regular methods.

2022-09-23 16:59 UTC, divagant-martian commented
Oh this is great! As a user this would help in that rust analyzer (or any lsp) will finally suggest these methods

2022-09-23 17:26 UTC, amanjeev approved these changes
I approve, but will defer to @emilio.

2022-09-27 19:14 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #2282) made this pull request unmergeable. Please resolve the merge conflicts.

2022-10-04 15:28 UTC, emilio requested changes
I still tend to think that this is very complex for the value it provides, but at the very least some things need to be fixed.

2022-10-04 15:28 UTC, emilio commented on src/codegen/mod.rs
> +        if is_variadic & ctx.options().tuple_varargs_len.is_none() {
Why the bitwise `&`? Probably just `&&` right?

2022-10-04 15:28 UTC, emilio commented on src/codegen/mod.rs
> +    variadic_methods: HashMap<Ident, VariadicMethodInfo>,
This can't be a hash map. We do need consistent iteration order.

2022-10-05 02:00 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably #2284) made this pull request unmergeable. Please resolve the merge conflicts.

2022-11-02 20:33 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably 9c32b460481903d90c6ac5df277bfa853a0558d8) made this pull request unmergeable. Please resolve the merge conflicts.

2022-11-11 16:37 UTC, closed without merging