Add `TypeKind::Qualified` and remove `Type::is_const`
rust-lang/rust-bindgen pull request #2350
Opened 2022-11-16 19:54 UTC by pvdrz

2022-11-30 12:28 UTC, emilio requested changes
So, generally it looks fine. I expected it to simplify some other places a bit more, specially since we still need to store the type name and layout in two places...

So I'm not convinced this is _quite_ worth it anymore, but if we want to land this at least we should factor out the qualification stuff to its own function so it isn't so repetitive...

2022-11-30 12:28 UTC, emilio commented on bindgen/ir/context.rs
> +        let ty = Type::new(name.clone(), layout.clone(), type_kind);
nit: just `layout` as per the clippy thing.

2022-11-30 12:28 UTC, emilio commented on bindgen/ir/ty.rs
> +        if is_const {
So we should be able to abstract this into a `maybe_qualify` helper or something. Otherwise it feels very clunky, wdyt?

2022-12-07 11:18 UTC, emilio requested changes

2022-12-07 18:37 UTC, pvdrz commented on bindgen/ir/ty.rs
> +    pub(crate) fn maybe_qualify(
You're right. I documented the function and avoided returning the id.

2022-12-15 21:05 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably 87b535c3c1089a09632e4d3a1541bd53bb40f55e) made this pull request unmergeable. Please resolve the merge conflicts.

2023-01-06 18:10 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably 5875949e8e598fa9b0e3a018b3547815e2654fc8) made this pull request unmergeable. Please resolve the merge conflicts.

2023-01-12 20:40 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably ed2d06eae31e94022961ef4ed1d8c784b3bc00d4) made this pull request unmergeable. Please resolve the merge conflicts.

2023-07-05 15:22 UTC, closed without merging