Escape spaces in the depfile output
rust-lang/rust-bindgen pull request #2503
Opened 2023-04-12 20:40 UTC by danakj

Header file paths included from C/C++ files may include spaces in them, and if they do, the spaces need to be escaped in order to generate a proper depfile. Otherwise, the dep file ends up pointing to non-existant paths.

For example:
../../third_party/depot_tools/win_toolchain/vs_files/27370823e7\Windows Kits\10\Include\10.0.22621.0\shared\winapifamily.h

This path ends up being parsed as two files, neither of which exist: ../../third_party/depot_tools/win_toolchain/vs_files/27370823e7\Windows Kits\10\Include\10.0.22621.0\shared\winapifamily.h

This leads to build failures with ninja when it's verifying that the build is complete:
```
$ ninja -C out rust_mojo_unittests -w dupbuild=err -n -d explain
ninja explain: output ../../third_party/depot_tools/win_toolchain/vs_files/27370823e7\Windows doesn't exist
ninja explain: output Kits/10/Include/10.0.22621.0/shared/winapifamily.h is dirty
```

ninja accepts spaces being escaped with backslash, so the path Windows Kits\10\Include\10.0.22621.0\shared\winapifamily.h can be valid if escaped as:

Windows\ Kits\10\Include\10.0.22621.0\shared\winapifamily.h

However this is less clear for humans as there is inconsistent use of backslashes, so we opt to escape backslashes as well, which ninja also accepts, and is standard for Windows paths.

Windows\ Kits\\10\\Include\\10.0.22621.0\\shared\\winapifamily.h

2023-04-12 21:06 UTC, danakj commented
Filed issue #2504 which this PR can resolve.

2023-04-12 21:08 UTC, danakj commented
r? @fitzgen

2023-04-13 17:47 UTC, pvdrz commented
@danakj excuse me if I'm missing something but it isn't more straightforward to use [`str::replace`](https://doc.rust-lang.org/std/primitive.str.html#method.replace)?

2023-04-13 18:18 UTC, danakj commented
Yes, it would. Cool, I failed to find that function. Though I will note that it will require some String allocations to use that instead of simply iterating over the chars. Probably.. this is fine..?

If you're able to review/approve, then I assume you have a preference for it and I can switch to that. Otherwise, I can do either one.

2023-04-13 18:23 UTC, pvdrz commented
Yeah you'd have to do several allocations to handle all the escapes which is not ideal but I don't expect this part of the code to be performance critical and I'd be more inclined to have shorter and more concise code handling this.

I can do a proper review later, let me know when the `replace` change is done :)

2023-04-13 19:03 UTC, danakj commented
Ok thanks for the quick feedback. I've used `replace()` now.

2023-04-13 19:09 UTC, pvdrz requested changes
There are some clippy warnings about using single character strings for patterns. e.g. using `" "` instead of `' '`. Could you fix those?

Also  could you add a new entry to `CHANGELOG.md` explaining this change?

2023-04-13 19:09 UTC, pvdrz commented on bindgen/deps.rs
> +            buf = format!("{} {}", buf, escape(&file));
I think this `&` is not necessary.

2023-04-13 19:37 UTC, danakj commented on bindgen/deps.rs
> +            buf = format!("{} {}", buf, escape(&file));
You're right. Done.

2023-04-13 19:38 UTC, danakj commented
Clippy should be happy now, and CHANGELOG updated (which meant rebasing).

2023-04-13 19:40 UTC, pvdrz approved these changes

2023-04-13 19:59 UTC, danakj commented
Thank you for reviewing :)

2023-04-14 00:06 UTC, merged