C unwind is stable
rust-lang/rust-bindgen pull request #2591
Opened 2023-07-25 20:25 UTC by tshepang

Closes #2581

2023-07-26 01:46 UTC, pvdrz requested changes
Could you update the `bindgen-tests/tests/expectations/tests/c-unwind-abi-override-nightly.rs and `bindgen-tests/tests/expectations/tests/c-unwind-abi-override.rs` tests so we can test this?

2023-07-26 05:34 UTC, tshepang commented
Did changes, but not clear why `abi_thiscall` feature was part of the test (so I removed it).

Am also not happy with my changelog entry... happy to hear suggestions.

2023-07-26 16:26 UTC, pvdrz commented
> Did changes, but not clear why `abi_thiscall` feature was part of the test (so I removed it).
I suspect some dummy forgot to change the feature when they copied the tests for c_unwind (I'm 99% sure I'm that dummy)
 
> Am also not happy with my changelog entry... happy to hear suggestions.
Maybe something like: The `c_unwind` ABI can be used without a feature gate for any rust target version greater or equal to 1.71

2023-07-26 16:54 UTC, pvdrz commented on bindgen/features.rs
> +                f_nightly.vectorcall_abi
Maybe add this:
```rust
let f_1_68 = RustFeatures::from(RustTarget::Stable_1_68);
assert!(f_1_68.abi_efiapi && !f_1_68.c_unwind_abi);
```

2023-07-27 03:37 UTC, pvdrz approved these changes

2023-07-27 03:37 UTC, merged