Update minimum regex version to fix compile error
rust-lang/rust-bindgen pull request #2717
Opened 2024-01-12 04:15 UTC by kawasin73

regex 1.5.3 solves the compile error with unicode-perl feature. https://github.com/rust-lang/regex/blob/master/CHANGELOG.md#153-2021-05-01

Specifing wrong version as the minimum version can cause compile errors on products which depend on bindgen. Minimum versions can be checked with this cargo command.

```
cargo +nightly update -Z minimal-versions
```

2024-01-12 04:20 UTC, kawasin73 commented
r? @emilio

2024-01-12 21:51 UTC, tgross35 commented
I think you may as well go all the way up to version 1.9.6, which has a lot more bugfixes and is the last version to support bindgen's MSRV of 1.60

2024-01-12 21:52 UTC, tgross35 requested changes

2024-01-12 21:52 UTC, tgross35 commented on bindgen/Cargo.toml
> +regex = { version = "1.5.3", default-features = false, features = ["std", "unicode-perl"] }
```suggestion
regex = { version = "1.9.6", default-features = false, features = ["std", "unicode-perl"] }
```

2024-01-12 21:55 UTC, tgross35 commented
Ah, this is actually a duplicate of #2714

2024-01-12 22:13 UTC, closed without merging

2024-01-12 22:14 UTC, emilio commented
Let's close as a dup. Happy to take a patch updating to a newer regex version, though given users can use the very latest it's not a big deal.

2024-01-12 22:14 UTC, bors-servo commented
:umbrella: The latest upstream changes (presumably 11aeae4875af5d078db77106fcd3caf4a59c4227) made this pull request unmergeable. Please resolve the merge conflicts.

2024-01-15 01:38 UTC, kawasin73 commented
Even with regex `1.5.1`, bindgen still fails to build with minimum versions. Re-create the PR at #2721.