Fix generated constants: f64::INFINITY & f64::NEG_ INFINITY
rust-lang/rust-bindgen pull request #2854
Opened 2024-06-25 07:09 UTC by gabiganam

https://github.com/rust-lang/rust-bindgen/issues/2853

2024-06-25 07:54 UTC, eifrah-aws requested changes

2024-06-25 07:54 UTC, eifrah-aws commented on bindgen/codegen/helpers.rs
> +    pub(crate) fn float_expr(f: f64) -> Result<TokenStream, ()> {
According to this https://rust-lang.github.io/rust-clippy/master/index.html#/legacy_numeric_constants
This fix should also be applied for `f32` et al

2024-06-25 19:29 UTC, madsmtm reviewed
I'm not sure of Bindgen's MSRV policy for generated crates, but these constants require at least Rust 1.43.

2024-06-25 21:29 UTC, pvdrz commented
> I'm not sure of Bindgen's MSRV policy for generated crates, but these constants require at least Rust 1.43.

If that's the case, there should be a new variant in `RustTarget` representing 1.43 and this change should be gated behind a feature that enables if the target version is larger or equal than 1.43

2024-06-26 07:00 UTC, gabiganam commented
> > I'm not sure of Bindgen's MSRV policy for generated crates, but these constants require at least Rust 1.43.
> 
> If that's the case, there should be a new variant in `RustTarget` representing 1.43 and this change should be gated behind a feature that enables if the target version is larger or equal than 1.43

Updated the PR, hope this is what you meant.

2024-06-27 14:16 UTC, madsmtm commented
> @gabiganam requested a review from @madsmtm

Sorry, I'm the wrong person to ask for this, I'm not a maintainer here.

2024-06-27 15:54 UTC, pvdrz requested changes
This looks good to me. Could you please add this change to the changelog?

2024-07-02 14:08 UTC, pvdrz approved these changes

2024-07-02 14:12 UTC, merged