Add support for custom attributes
rust-lang/rust-bindgen pull request #2866
Opened 2024-07-08 14:53 UTC by mkroening

This adds support for custom attributes:

- `ParseCallbacks::add_attributes(&self, info: &AttributeInfo<'_>) -> Vec<TokenStream>`
- `--with-attribute-custom <CUSTOM>`
- `--with-attribute-custom-struct <CUSTOM>`
- `--with-attribute-custom-enum <CUSTOM>`
- `--with-attribute-custom-union <CUSTOM>`

The implementation is very similar to the custom derives functionality. One thing I am not sure about is returning `Vec<TokenStream>` instead of `Vec<String>`, but that seemed natural to me.

Fixes https://github.com/rust-lang/rust-bindgen/issues/2520

2024-08-22 16:45 UTC, pvdrz requested changes
Hi @mkroening sorry for the delay with the review. 

I only have two requests for you because otherwise this looks great:
- It is better to use `String` instead of `TokenStream` as the latter leaks `proc_macro2` into our public API, meaning that we would have to do releases from time to time just to keep up to date with `proc_macro2`.
- There should be a test for the CLI args and also some documentation explaining the syntax of the attributes as right now.

Edit: I also have an additional question for you that is non-blocking and can be addressed later (even by someone else). Would it be possible to re-implement the custom derives functionality using the custom attributes machinery instead?

2024-08-29 10:28 UTC, mkroening commented
Thanks for the review!

> * It is better to use `String` instead of `TokenStream` as the latter leaks `proc_macro2` into our public API, meaning that we would have to do releases from time to time just to keep up to date with `proc_macro2`.

✅ 

> * There should be a test for the CLI args 

✅ 

> and also some documentation explaining the syntax of the attributes as right now.

Where would I put that? I did not find anything similar for `--with-derive-custom`.

> Would it be possible to re-implement the custom derives functionality using the custom attributes machinery instead?

That should be possible! Would you like me to tackle this in this PR or in a separate one?

I have also implemented support for annotations, but error reporting is difficult there. It currently panics, if the attribute is not parsable as `TokenStream`.

2024-08-29 21:00 UTC, pvdrz commented
> 
> > and also some documentation explaining the syntax of the attributes as right now.
> 
> Where would I put that? I did not find anything similar for `--with-derive-custom`.

This would go in `bindgen-cli` as part of the docstring for the respective fields so `clap` can generate the `--help` message with that documentation. This is how it looks for the `--with-derive-custom.*` flags:
```text
$ bindgen --help
Generates Rust bindings from C/C++ headers.

Usage: bindgen <FLAGS> <OPTIONS> <HEADER> -- <CLANG_ARGS>...

Arguments:
  [HEADER]         C or C++ header file
  [CLANG_ARGS]...  Arguments to be passed straight through to clang

Options:
      ...
      --with-derive-custom <CUSTOM>
          Derive custom traits on any kind of type. The CUSTOM value must be of the shape REGEX=DERIVE where DERIVE is a coma-separated list of derive macros
      --with-derive-custom-struct <CUSTOM>
          Derive custom traits on a `struct`. The CUSTOM value must be of the shape REGEX=DERIVE where DERIVE is a coma-separated list of derive macros
      --with-derive-custom-enum <CUSTOM>
          Derive custom traits on an `enum. The CUSTOM value must be of the shape REGEX=DERIVE where DERIVE is a coma-separated list of derive macros
      --with-derive-custom-union <CUSTOM>
          Derive custom traits on a `union`. The CUSTOM value must be of the shape REGEX=DERIVE where DERIVE is a coma-separated list of derive macros
```
> > Would it be possible to re-implement the custom derives functionality using the custom attributes machinery instead?
> 
> That should be possible! Would you like me to tackle this in this PR or in a separate one?

I'd do it on a separate one so it is easier to review and track. 

Thanks!

2024-08-30 13:30 UTC, mkroening commented
> This would go in `bindgen-cli` as part of the docstring for the respective fields so `clap` can generate the `--help` message with that documentation. This is how it looks for the `--with-derive-custom.*` flags:

Ah, that's what you mean. I wondered, since I had already done that when opening this PR. Perhaps you overlooked it?

I have also fixed the formatting for CI.

2024-08-30 19:04 UTC, pvdrz commented
Oh my bad, it seems my head just skipped that section of code :rofl:. It seems there are some compilation errors due to the change from `TokenStream` to `String`, could you fix those so we can roll this up?. Thanks!

2024-08-31 11:27 UTC, mkroening commented
The CI is green now. :)

2024-09-03 14:10 UTC, pvdrz approved these changes

2024-09-03 14:15 UTC, merged